# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogLogin(object):
    def setupUi(self, DialogLogin):
        DialogLogin.setObjectName("DialogLogin")
        DialogLogin.resize(400, 541)
        DialogLogin.setStyleSheet("#DialogLogin {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.534, x2:1, y2:0.528, stop:0 rgba(237, 66, 59, 255), stop:1 rgba(169, 40, 182, 255))\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DialogLogin)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(DialogLogin)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.LabelTitle = QtWidgets.QLabel(self.widget)
        self.LabelTitle.setStyleSheet("#LabelTitle{\n"
"    font-size: 30px;\n"
"    font-weight:700;\n"
"    color: rgb(255, 255, 255);\n"
"    background:transparent;\n"
"}")
        self.LabelTitle.setObjectName("LabelTitle")
        self.horizontalLayout.addWidget(self.LabelTitle)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(DialogLogin)
        self.widget_2.setStyleSheet("#WidgetEditEmail, #WidgetEditPassword {\n"
"    background: transparent;\n"
"    color: white;\n"
"    border-bottom: 2px;\n"
"    border-style: solid;\n"
"    border-color: rgb(10, 10, 10);\n"
"    font-weight:700;\n"
"    padding-top: 0px\n"
"}\n"
"\n"
"#WidgetEditEmail QLineEdit, #WidgetEditPassword QLineEdit{\n"
"    background: transparent;\n"
"    color: white;\n"
"    border: 0px;\n"
"    border-style: solid;\n"
"    border-color: rgb(10, 10, 10);\n"
"    font-size:20px;\n"
"    font-weight:600;\n"
"    padding-top: 0px\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setSpacing(14)
        self.verticalLayout.setObjectName("verticalLayout")
        self.WidgetEditEmail = QtWidgets.QWidget(self.widget_2)
        self.WidgetEditEmail.setObjectName("WidgetEditEmail")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.WidgetEditEmail)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.WidgetEditEmail)
        self.label_2.setMinimumSize(QtCore.QSize(30, 30))
        self.label_2.setMaximumSize(QtCore.QSize(30, 30))
        self.label_2.setStyleSheet("background:transparent;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icons/MdiEmail.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setIndent(0)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.EditEmail = QtWidgets.QLineEdit(self.WidgetEditEmail)
        self.EditEmail.setStyleSheet("")
        self.EditEmail.setObjectName("EditEmail")
        self.horizontalLayout_2.addWidget(self.EditEmail)
        self.verticalLayout.addWidget(self.WidgetEditEmail)
        self.WidgetEditPassword = QtWidgets.QWidget(self.widget_2)
        self.WidgetEditPassword.setStyleSheet("")
        self.WidgetEditPassword.setObjectName("WidgetEditPassword")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.WidgetEditPassword)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.WidgetEditPassword)
        self.label_3.setMinimumSize(QtCore.QSize(30, 30))
        self.label_3.setMaximumSize(QtCore.QSize(30, 30))
        self.label_3.setStyleSheet("background:transparent;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/icons/Candado.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.EditPassword = QtWidgets.QLineEdit(self.WidgetEditPassword)
        self.EditPassword.setStyleSheet("")
        self.EditPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.EditPassword.setObjectName("EditPassword")
        self.horizontalLayout_3.addWidget(self.EditPassword)
        self.verticalLayout.addWidget(self.WidgetEditPassword)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.ButtonLogin = QtWidgets.QPushButton(self.widget_2)
        self.ButtonLogin.setMinimumSize(QtCore.QSize(0, 42))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.ButtonLogin.setFont(font)
        self.ButtonLogin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ButtonLogin.setStyleSheet("#ButtonLogin{\n"
"    background-color:rgb(49, 29, 41);\n"
"    color: rgb(255, 255, 255);\n"
"    padding:10px;\n"
"    border-radius:21px;\n"
"    font-weight:700;\n"
"    font-size:13px\n"
"}")
        self.ButtonLogin.setObjectName("ButtonLogin")
        self.verticalLayout.addWidget(self.ButtonLogin)
        self.verticalLayout_2.addWidget(self.widget_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 157, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.widget_3 = QtWidgets.QWidget(DialogLogin)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("background:transparent")
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/MdiEmail.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("background:transparent")
        self.pushButton_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/MdiFacebook.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("background:transparent")
        self.pushButton_4.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/MdiApple.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_2.addWidget(self.widget_3)

        self.retranslateUi(DialogLogin)
        QtCore.QMetaObject.connectSlotsByName(DialogLogin)

    def retranslateUi(self, DialogLogin):
        _translate = QtCore.QCoreApplication.translate
        DialogLogin.setWindowTitle(_translate("DialogLogin", "Dialog"))
        self.LabelTitle.setText(_translate("DialogLogin", "Iniciar Sesion"))
        self.EditEmail.setPlaceholderText(_translate("DialogLogin", "Correo electronico"))
        self.EditPassword.setPlaceholderText(_translate("DialogLogin", "contraseña"))
        self.ButtonLogin.setText(_translate("DialogLogin", "INICIAR SESION"))
import interface_rc
